---
- name: Automatisation de la création de la VM sur Proxmox
  hosts: proxmox
  gather_facts: false

  tasks:
    - name: 1. Création de la machine virtuelle Lubuntu
      community.proxmox.proxmox_kvm:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        validate_certs: false
        node: "node0esieeit"
        name: "Lubuntu-VM"
        vmid: 200
        memory: 512
        cores: 2
        sockets: 1
        ide:
          ide2: "local:iso/lubuntu-16.04.6-desktop-amd64.iso,media=cdrom"
        scsihw: virtio-scsi-pci
        scsi:
          scsi0: "local-lvm:10"
        net:
          net0: "virtio,bridge=vmbr0"
        state: present
      delegate_to: localhost

    - name: 2. Démarrage de la machine virtuelle
      community.proxmox.proxmox_kvm:
        api_host: "{{ api_host }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        validate_certs: false
        node: "node0esieeit"
        vmid: 200
        state: started
      delegate_to: localhost
